### Get request with a header and parameters
GET http://localhost:8080/questions?page=0&size=2&sort=createdAt,desc
Accept: application/json

### Send POST request with json body
POST http://localhost:8080/questions
Content-Type: application/json

{
  "title": "How to use PostgreSQL with Spring Boot and JPA",
  "description": "i want to use PostgreSQL with Spring Boot and JPA and devolop RESTful APIs. Please help!"
}

### Send PUT request with json body
PUT http://localhost:8080/questions/1000
Content-Type: application/json

{
  "title": "How to use PostgreSQL with Spring Boot and JPA",
  "description": "i want to use PostgreSQL with Spring Boot and JPA and devolop RESTful APIs. Please help!"
}

### Send DELETE request with parameters
DELETE http://localhost:8080/questions/1000

###

